# nginx yaml for proxy pass
#
version: '3.9'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      # htpasswd -bBc ../.htpasswd username password
      - ../.htpasswd:/etc/nginx/.htpasswd
      # - ./nginx/log:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - notebook
      - rsshub
      - ical4notion
      - rag