# nginx yaml for proxy pass
#
version: '3.9'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      # - ./nginx/log:/var/log/nginx
    depends_on:
      - rsshub
      - ical4notion
